server:
  port: 7788
  
spring:
  application:
    name: woniu58-auth  #当前项目名，微服务的名字   非常重要
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
      
eureka:
  client:
    service-url: 
      defaultZone: http://eurekaserver9001.com:9001/eureka/
  instance: 
    instance-id: woniu58-auth-7788 #配置中心中显示微服务的名称
    prefer-ip-address: true   #是否显示访问微服务的url（可选）
  

    